# Generated by Django 4.1.6 on 2023-04-10 09:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('sn', models.CharField(max_length=64)),
                ('const_year', models.SmallIntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1900)])),
                ('intern_symbol', models.CharField(max_length=64)),
                ('intern_no', models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)])),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Fair'), (4, 'Poor')], default=2)),
                ('group', models.ForeignKey(default='Not specified', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='register.group')),
                ('location', models.ForeignKey(default='Not defined', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='area', to='register.location')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('closeDate', models.DateTimeField(blank=True, null=True)),
                ('issue', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New request'), (2, 'Start work'), (3, 'Hold'), (4, 'Done')], default=1)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineRequest', to='register.machine')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userRequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=64)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailedLocation', to='register.location')),
            ],
        ),
    ]
