# Generated by Django 4.1.6 on 2023-04-10 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_group_location_machine_request_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicianRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
